kind: Service
apiVersion: v1
metadata:
  name: boot-frontend
spec:
  selector:
    app: boot-frontend
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8086
    nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-resource-app
spec:
  selector:
      matchLabels:
        app: boot-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: boot-frontend
    spec:
      containers:
        - name: boot-resource-app-c
          image: boot-resource-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8086