kind: Service
apiVersion: v1
metadata:
  name: boot-frontend
spec:
  selector:
    app: boot-frontend
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8086
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-resource-app
spec:
  selector:
      matchLabels:
        app: boot-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: boot-frontend
    spec:
      containers:
        - name: boot-resource-app-c
          image: gcr.io/invertible-tree-252704/boot-resource-app:latest
          ports:
            - containerPort: 8086
