kind: Service
apiVersion: v1
metadata:
  name: bus-search-service
spec:
  selector:
    app: bus-search-srvc
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8099
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bus-search-srvc-d
spec:
  selector:
      matchLabels:
        app: bus-search-srvc
  replicas: 1
  template:
    metadata:
      labels:
        app: bus-search-srvc
    spec:
      containers:
        - name: bus-search-srvc-c
          image: gcr.io/invertible-tree-252704/bus-search-srvc-img:latest
          ports:
            - containerPort: 8099
