kind: Service
apiVersion: v1
metadata:
  name: bus-srvc-web-app-s
spec:
  selector:
    app: bus-app-srvc
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bus-srvc-web-app-d
spec:
  selector:
      matchLabels:
        app: bus-app-srvc
  replicas: 1
  template:
    metadata:
      labels:
        app: bus-app-srvc
    spec:
      containers:
        - name: bus-srvc-web-app-c
          image: gcr.io/invertible-tree-252704/bus-srvc-web-app-img:latest
          ports:
            - containerPort: 8080
